/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Character = { 'amy' : null } |
  { 'tails' : null } |
  { 'shadow' : null } |
  { 'sonic' : null } |
  { 'knuckles' : null };
export interface PlayerProgress {
  'currentRings' : bigint,
  'totalRingsCollected' : bigint,
}
export interface Score { 'player' : Principal, 'score' : bigint }
export interface _SERVICE {
  'addRings' : ActorMethod<[bigint], undefined>,
  'getLeaderboard' : ActorMethod<[string], Array<Score>>,
  'getPlayerProgress' : ActorMethod<[], PlayerProgress>,
  'getUnlockedCharacters' : ActorMethod<[], Array<Character>>,
  'spendRings' : ActorMethod<[Character], undefined>,
  'updateHighScore' : ActorMethod<[string, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];