/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Score = IDL.Record({
  'player' : IDL.Principal,
  'score' : IDL.Nat,
});
export const PlayerProgress = IDL.Record({
  'currentRings' : IDL.Nat,
  'totalRingsCollected' : IDL.Nat,
});
export const Character = IDL.Variant({
  'amy' : IDL.Null,
  'tails' : IDL.Null,
  'shadow' : IDL.Null,
  'sonic' : IDL.Null,
  'knuckles' : IDL.Null,
});

export const idlService = IDL.Service({
  'addRings' : IDL.Func([IDL.Nat], [], []),
  'getLeaderboard' : IDL.Func([IDL.Text], [IDL.Vec(Score)], ['query']),
  'getPlayerProgress' : IDL.Func([], [PlayerProgress], []),
  'getUnlockedCharacters' : IDL.Func([], [IDL.Vec(Character)], ['query']),
  'spendRings' : IDL.Func([Character], [], []),
  'updateHighScore' : IDL.Func([IDL.Text, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Score = IDL.Record({ 'player' : IDL.Principal, 'score' : IDL.Nat });
  const PlayerProgress = IDL.Record({
    'currentRings' : IDL.Nat,
    'totalRingsCollected' : IDL.Nat,
  });
  const Character = IDL.Variant({
    'amy' : IDL.Null,
    'tails' : IDL.Null,
    'shadow' : IDL.Null,
    'sonic' : IDL.Null,
    'knuckles' : IDL.Null,
  });
  
  return IDL.Service({
    'addRings' : IDL.Func([IDL.Nat], [], []),
    'getLeaderboard' : IDL.Func([IDL.Text], [IDL.Vec(Score)], ['query']),
    'getPlayerProgress' : IDL.Func([], [PlayerProgress], []),
    'getUnlockedCharacters' : IDL.Func([], [IDL.Vec(Character)], ['query']),
    'spendRings' : IDL.Func([Character], [], []),
    'updateHighScore' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };